appName: "Alerting Service"

metricSourceClients: !!map
  GRAPHITE: "com.flipkart.alert.storage.GraphiteHttpClient"
  TSDB: "com.flipkart.alert.storage.TsdbHttpClient"
  HttpToFlatJson: "com.flipkart.alert.storage.HttpToFlatJsonClient"

http:
  port: 8888
  adminPort: 8881
  rootPath: "/alertz/*"

statusDispatcherServiceConfiguration:
  poolSize: 25
  queueSize: 10000
  targetConfigs: !!map
    MAIL:
      className: "com.flipkart.alert.dispatch.MailStatusDispatcher"
      defaultParams: !!map
        mail.smtp.host: "localhost"
        mail.smtp.port: "25"
        from: "alert-service@flipkart.com"
    HTTP:
      className: "com.flipkart.alert.dispatch.HttpQueueStatusDispatcher"
      defaultParams: !!map
        defaultQueue: "defaultQueue"

ruleEventsConfiguration:
  poolSize: 15
  queueSize: 10000

metricArchiverConfiguration:
  enabled: true
  metricArchiverClass: "com.flipkart.alert.storage.archiver.RRD4JFileMetricArchiver"
  params: !!map
    basePath: "./"

graphiteConfiguration:
  host: "flo-cache1.stage.ch.flipkart.com"
  port: 2003
  prefix: "alertz"
  env: "local"

logging:
  console:
    enabled: true
    threshold: ALL
  file:
    enabled: false
    threshold: ALL
    timeZone: IST
    logFormat: "%highlight(%-5level) [%date] [%thread] [%cyan(%logger{0})]: %message%n"
    currentLogFilename: /var/log/flipkart/alertz/alertz.log
    archivedLogFilenamePattern: /var/log/flipkart/alertz/alertz-%d.log.gz
    archivedFileCount: 10