appName: "Alerting Service"

metricSourceClients: !!map
  GRAPHITE: "com.flipkart.alert.storage.GraphiteHttpClient"
  TSDB: "com.flipkart.alert.storage.TsdbHttpClient"
  CAS: "com.flipkart.alert.storage.health.CasHttpClient"
  HttpToFlatJson: "com.flipkart.alert.storage.HttpToFlatJsonClient"

metricArchiverConfiguration:
  enabled: true
  metricArchiverClass: "com.flipkart.alert.storage.archiver.RRD4JFileMetricArchiver"
  params: !!map
    basePath: "./"

statusDispatcherServiceConfiguration:
  poolSize: 25
  queueSize: 10000
  targetConfigs: !!map
    MAIL:
      className: "com.flipkart.alert.dispatch.MailStatusDispatcher"
      defaultParams: !!map
        mail.smtp.host: "localhost"
        mail.smtp.port: "25"
        from: "alert-service@flipkart.com"
    HTTP:
      className: "com.flipkart.alert.dispatch.HttpQueueStatusDispatcher"
      defaultParams: !!map
        defaultQueue: "defaultQueue"

ruleEventsConfiguration:
  poolSize: 15
  queueSize: 10000