appName: "Flipkart Rule Processing Engine"

metricSourceClients: !!map
  GRAPHITE: "com.flipkart.alert.storage.GraphiteHttpClient"
  TSDB: "com.flipkart.alert.storage.TsdbHttpClient"
  CAS: "com.flipkart.alert.storage.health.CasHttpClient"
  HttpToFlatJson: "com.flipkart.alert.storage.HttpToFlatJsonClient"

metricArchiverConfiguration:
  enabled: true
  metricArchiverClass:TSDBArchiver
  params: !!map
    basePath: "./"

dispatcherConfiguration:
  poolSize: 25
  queueSize: 10000
  targetConfigs: !!map
    MAIL:
      className: "com.flipkart.alert.dispatch.MailStatusDispatcher"
      defaultParams: !!map
        mail.smtp.host: "localhost"
        mail.smtp.port: "25"
        from: "alert-service@flipkart.com"
    HTTP:
      className: "com.flipkart.alert.dispatch.HttpQueueStatusDispatcher"
      defaultParams: !!map
        defaultQueue: "defaultQueue"
    NAGIOS:
      className: "com.flipkart.alert.dispatch.NagiosDispatcher"
      defaultParams: !!map
        nsca_wrapper: "/usr/lib/nagios/plugins/fk-ops-nsca-wrapper/nsca_wrapper"
        IP: "10.65.100.85:10.65.100.86"
        host: "fk-w3-alertservice1"
        binary: "/usr/sbin/send_nsca"
        config: "/etc/send_nsca.cfg"
        nagiosHelper: "/bin/fk-alert-service/nagios_helper.sh"

ruleEventsConfiguration:
  poolSize: 15
  queueSize: 10000