appName: "Flipkart Alerting Service"

metricSourceClients: !!map
  GRAPHITE: "com.flipkart.alert.storage.GraphiteHttpClient"
  TSDB: "com.flipkart.alert.storage.TsdbHttpClient"
  CAS: "com.flipkart.alert.storage.health.CasHttpClient"
  HttpToFlatJson: "com.flipkart.alert.storage.HttpToFlatJsonClient"

http:
  port: 8888
  adminPort: 8881
  rootPath: "/fk-alert-service/*"

statusDispatcherServiceConfiguration:
  poolSize: 25
  queueSize: 10000
  targetConfigs: !!map
    MAIL:
      className: "com.flipkart.alert.dispatch.MailStatusDispatcher"
      defaultParams: !!map
        mail.smtp.host: "localhost"
        mail.smtp.port: "25"
        from: "alert-service@flipkart.com"
    HTTP:
      className: "com.flipkart.alert.dispatch.HttpQueueStatusDispatcher"
      defaultParams: !!map
        defaultQueue: "defaultQueue"
    NAGIOS:
      className: "com.flipkart.alert.dispatch.NagiosDispatcher"
      defaultParams: !!map
        nsca_wrapper: "/usr/lib/nagios/plugins/fk-ops-nsca-wrapper/nsca_wrapper"
        IP: "10.65.100.85:10.65.100.86"
        host: "fk-w3-alertservice1"
        binary: "/usr/sbin/send_nsca"
        config: "/etc/send_nsca.cfg"
        nagiosHelper: "/bin/fk-alert-service/nagios_helper.sh"

ruleEventsConfiguration:
  poolSize: 15
  queueSize: 10000

metricArchiverConfiguration:
  enabled: true
  metricArchiverClass:"com.flipkart.alert.storage.archiver.RRD4JFileMetricArchiver"
  params: !!map
    basePath: "./"

graphiteConfiguration:
  host: "flo-graphite.nm.flipkart.com"
  port: 80
  prefix: "alertz"
  env: "nm"

logging:
  console:
    enabled: false
    threshold: ALL
  file:
    enabled: true
    threshold: ALL
    timeZone: IST
    logFormat: "%highlight(%-5level) [%date] [%thread] [%cyan(%logger{0})]: %message%n"
    currentLogFilename: /var/log/flipkart/fk-alert-service/fk-alert-service.log
    archivedLogFilenamePattern: /var/log/flipkart/fk-alert-service/fk-alert-service-%d.log.gz
    archivedFileCount: 10
